### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by frehage** [E2-PhD-Council/ThesisTemplate#5]
Necessary comments:
  * replace all \label commands with \paperlabel in papers to avoid multiply-defined labels

**Comment by krooken** [comment]
I have made changes to AddMyPapers that I think solves this issue by redefining \label and \ref. I think that is a bit nicer than having to search and replace all occurences of \label in the appended papers. All \ref and \eqref would otherwise also need to be changed such that the label is prefixed with the paper name.

So far my changes work for the appended papers that I have used, but there are surely more situations that need to be considered. I have added example usage that have triggered warnings or inconsistencies when I have used the template. See #11, #15 and #16.

**Comment by jackonelli** [comment]
I will have a look at it as soon as possible!
